version: '3.9'

services:
  app:
    image: ghcr.io/bombnp/cleverse-hackathon/speech-stroop-backend:latest
    container_name: speech-stroop-backend
    restart: unless-stopped
    env_file: .env
    ports:
      - 3000:3000
