version: '3.9'

services:
  mongo:
    image: mongo:latest
    container_name: speech-stroop-mongo
    restart: unless-stopped
    volumes:
      - ./volumes/mongo:/data/db
    ports:
      - 27017:27017
